global:
  domain: liberia-builds.digit.org ## Add your Domain Name Eg: site.mydomain.com
  setup: fullsetup
  
cluster-configs:
  namespaces:
    create: true
    values: [ jenkins, monitoring ]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"

jenkins:
  persistence:
    enabled: true
    azure:
      - diskName: "jenkins" ## add diskName
        diskUri: "/subscriptions/f07cf9be-deef-46d7-b025-fd11d032da4f/resourceGroups/MC_jenkins-cicd_jenkins-cicd_southafricanorth/providers/Microsoft.Compute/disks/jenkins"## Azure diskURI 

  oauth:
    enabled: true
    acl:
      admin:
        - HCM-LIBERIA-IMPL*liberia-devops
      user:
        - HCM-LIBERIA-IMPL*liberia-uat
       

  jobBuilder:
    repos: >-
      '' 
    # add ssh git repo link above
  deploymentJobs: 
    - name: egov-liberia-uat
      acl: [HCM-LIBERIA-IMPL*liberia-uat]   
    - name: egov-liberia-prod
      acl: [HCM-LIBERIA-IMPL*liberia-prod]                
    - name: ci
      acl: [HCM-LIBERIA-IMPL*liberia-devops]
    
       
  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    javaOpts: "-Xms2560M -Xmx2560M -Duser.timezone=Asia/Calcutta"

ingress-nginx:
  images:
    - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1
  replicas: 1
  default-backend-service: "egov/nginx"
  namespace: jenkins
  cert-issuer: "letsencrypt-prod"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"

cert-manager:
  namespace: jenkins
  clusterIssuer:
    stage:
      acme:
        email: "sai.prakash@egovernments.org"     # Add mail id

cluster-autoscaler:
  namespace: jenkins
  cloudProvider: azure  
  Location: South Africa North
  autoDiscovery:
    clusterName: jenkins-cicd # Add cluster name
    tags:
    - kubernetes.io/cluster/jenkins-cicd # Add cluster name
