cluster-configs:
    secrets:
        db:          # update the postgres db credentials
            username: azurepostgres
            password: demo1234  # must be more than 8 characters
            flywayUsername: azurepostgres
            flywayPassword: demo1234  # must be more than 8 characters
        egov-notification-sms: # To work sms notification service add the sms provider details
            username: demo
            password: demo
        egov-filestore:   # To work Filestore service add the IAM user details which has access on the filestore s3 bucket.
            aws-key: aswedfghew
            aws-secret-key: xdefghgdxc
        egov-location:  # To work Location service add your gmap key
            gmapskey: AIzaSyAQOd09-sdfegv
        egov-pg-service:    # To work pg service add your respective bank details
            axis-merchant-id: demo
            axis-merchant-secret-key: demo
            axis-merchant-user: demo
            axis-merchant-pwd: demo
            axis-merchant-access-code: demo
            payu-merchant-key: demo
            payu-merchant-salt: demo
        pgadmin:  # To work pgadmin service add details
            admin-email: demo@demo.com
            admin-password:  demo
            read-email: demo@demo.com
            read-password: demo
        egov-enc-service:  # To work egov-enc service add the details
            master-password: demo
            master-salt: q7.fr.cr
            master-initialvector: 9J&asfgrU-H2
        egov-notification-mail:  # To work mail notification service add respective mail details
            mailsenderusername: demo@demo
            mailsenderpassword: demo
        git-sync:   # To clone the config and mdms repos, Create github user and add your ssh private key below. This private should have access to config and mdms repo.  
            ssh: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIEpQIBAAKCAQEAlzLikQuNJNsmMnQgQfXnsgdx8cDNbAHJxCob6CK0UIvgB6P2
                t4zfBoaakIHjBEcmkSSJQSSTOMCmn0479i72vtnfLbZvHhg+37rDt9dJQlNNA+wU
                JNgjSLkWe6PwmkUaNF1kNmfM6bZ8SD4yGBdgWq/c0l8QpYNPh8hMJci7SyHLodeu
                SQ6jmQho+31U+6Q1F52lcoIf4Q9HeXBCCKlQwa6xo6p4fBtL+k0PYhLNZ5nFnybW
                v+hENBfHmE9j9GNO2mcFHyRnlG+Mqf4j7dpQ/ExMJ9CJeuPuZr/sATYMtK5xV5sz
                kSK6XwnKQLRxJLhYozU6YP3bZkcqkkovQL/QqwIDAQABAoIBAQCRPxuxdKRRTIkk
                HLRESSMbvdUzBSERaaJW5JDMblJDsiszi8pdR2GUVkgzG+NmX6dn9O45exZGhaNL
                FA+8Dh+Q9aFUu5WBFo+Hw1VyzMieg4FPjEFJp6w1l0BG5BUlTc6/kRvMu+h4d4pq
                p/zdcc9pLtn16ccHCN6ktMCZ53wszjnQJhga1vBpxQgsbbzH8aYyCs+1fqQatW+N
                zmCDoahd0aeN+RW3F2PWz+PIUdKLNHPwRogxLf/DQxVM+uX1vyqWI8bHXhr6WWJ1
                k/nyPeVRFyx1MSaFHwFPNy+Iaahyz4wjtjr0NHJeR1TwD8TSkY+0VErxEVfFFLvE
                xjOLlefxAoGBAOl7QPR7VJAh01T4r86csroc+osTCDRkp/aBmPKez7K+ZdVRwBFK
                CNt1tGVwXWNu+FXDGc7OhnTHiE1Id0UE37Ls7Lh7VOGwEoZjd9sXo8GNPhTKEqe3
                +UkRV3sRNyXVfXtJd/ZNYx3DghRevPbClKuC2ci/2N7y9L3lZKh3q3mjAoGBAKXI
                ClEJWKa8HuFx7iKwB/IpoHs1ufks94NgbPz7aNfoCmB4m44tnW7Wd7mDV/e1gCh0
                /2DwOwSu11vlXTfY1PpSG7XPKmghEj8jaRpUebZhbW8Pc49QCc/gyhsVfW+/pjQ8
                S+INa+jMXgGGnoRIiV1IF8BpdK57bZVu/vSlCc1ZAoGBAIBA1E138du6uPvUH76/
                FO5nPLlomvks0Zb3Wazsz+q/6/BiF79ni7YB0jZmouYb7w4tPd/8Up+Te6v4QowH
                QVpoCyDLnrTao1JvEUeolKudipyg4959kNIyVHul2UVPIL64fM0vdWLEIpBN+j8S
                Y9hS6I7904OksgweFkz0b51BAoGAENrIqbqAh9sibJtPsbkh5a3zwfMRaFL5CyNX
                kVTiMOlHfM1mS0s58VXesD65R9btI6/ZcvqZlX1NKeuk0ZO6+4QziwV380RBfafU
                /LdP9IntPVhd0Fk71iWthpllumHKvQ7QTDg/G1kDybXtEdfqF1DIEWjnUwH7fzDc
                vPS2jWkCgYEAzl3CS1XzElo+0C2P7RGPfLR8WdSnF14Ioln4guYgikFQfl6RfRV1
                rSxJEQKAXOlJ48u2QWbBlr0SKHHC1nWxhMPS+Rs1ATm7cKKu9e61oF740TaQcO9p
                tkdabl7fnX07Cr57Be8NbW1gNiNx0IGvn6oLlxnYVdjNQcOKkvZqR6o=
                -----END RSA PRIVATE KEY-----
            known-hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        kibana:    # Add Kibana details
            namespace: es-cluster
            credentials: demo
        egov-si-microservice:  # Add finance service details
            si-microservice-user: demo
            si-microservice-password: demo
            mail-sender-password: demo
        egov-edcr-notification:  # Add edcr service details
            edcr-mail-username: demo@demo.com
            edcr-mail-password: demo
            edcr-sms-username: demo
            edcr-sms-password: demo
        chatbot:     # Add chatbot details
            valuefirst-username: demo
            valuefirst-password: demo
        egov-user-chatbot:  # Add user chatbot details
            citizen-login-password-otp-fixed-value: "546941"
        oauth2-proxy:   # To work oauth2-proxy service, create and add your github OAuth Apps details
            clientID: qwgethjymnbv
            clientSecret: 3a08079easd9d8055470475696fd3baad5292
            cookieSecret: QVbnq0L8npoyfxZs96wtBg==
