# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/egov-liberia-uat-secrets.yaml$
          azure_keyvault: "https://demo-azure-terraform.vault.azure.net/keys/demo-azure-terraform/79b13dab991c43ad9877a5ebed76f1cf"
        - path_regex: environments/egov-liberia-prod-secrets.yaml$
          azure_keyvault: "https://demo-azure-terraform.vault.azure.net/keys/demo-azure-terraform/79b13dab991c43ad9877a5ebed76f1cf"
        - path_regex: environments/ci-secrets.yaml$
          azure_keyvault: "https://demo-azure-terraform.vault.azure.net/keys/demo-azure-terraform/79b13dab991c43ad9877a5ebed76f1cf"
